Test case auto
mintlayer/mojito_mobile_wallet pull request #80
Opened 2022-12-05 12:56 UTC by ZainAliSyed24

- Resolve  all test cases

2022-12-05 13:15 UTC, renie requested changes

2022-12-05 13:15 UTC, renie commented on .github/workflows/lint.yml
> +        run: npm test || npm test || npm test
This is here to automatically try running the tests again, to get another server.
Lets remove this multiple testing for now, evaluate how often that might happen, and we update it later if needed.
So, replace:
`run: npm test || npm test || npm test`
by
`run: npm test`

2022-12-05 14:38 UTC, renie approved these changes

2022-12-06 22:16 UTC, muursh approved these changes
Nothing stands out as troublesome here so if renie is happy so am I

2022-12-07 08:11 UTC, merged