minimum 500 sat condition and test cases
mintlayer/mojito_mobile_wallet pull request #81
Opened 2022-12-09 11:20 UTC by ZainAliSyed24

![Screenshot 2022-12-09 at 4 20 28 PM](https://user-images.githubusercontent.com/55507840/206691303-6a427252-cea1-484f-81a8-3c469957d0ea.png)

2022-12-13 18:37 UTC, renie requested changes

2022-12-13 18:37 UTC, renie commented on tests/integration/hd-segwit-bech32-wallet.test.js
> +    // maybe
Just remove this comment, please.

2022-12-14 07:45 UTC, ZainAliSyed24 commented on tests/integration/hd-segwit-bech32-wallet.test.js
> +    // maybe
removed @renie

2022-12-15 11:18 UTC, renie approved these changes

2022-12-15 11:29 UTC, merged