A-1202579766983042: sending amount value fix
mintlayer/mojito_mobile_wallet pull request #84
Opened 2023-01-09 16:18 UTC by owlsua

2023-01-13 09:09 UTC, ZainAliSyed24 approved these changes

2023-01-13 18:53 UTC, renie requested changes

2023-01-13 18:53 UTC, renie commented on screen/send/details.js
> +    const itemAmount = item.amount ? BigNumber(item.amount).toFormat().toString() : null;
The function `toFormat()` already returns a string. There is no need to call a `toString()`.

2023-01-14 12:20 UTC, renie approved these changes

2023-01-14 20:22 UTC, merged