trans issue and env setup
mintlayer/mojito_mobile_wallet pull request #85
Opened 2023-01-12 15:45 UTC by ZainAliSyed24

<img width="380" alt="Screenshot 2023-01-11 at 4 20 08 PM" src="https://user-images.githubusercontent.com/55507840/212112973-e8087102-a01e-4a56-a1f8-2a0d18efd505.png">

2023-01-13 14:55 UTC, owlsua approved these changes

2023-01-13 15:16 UTC, renie requested changes

2023-01-13 15:16 UTC, renie commented on babel.config.js
> +// module.exports = {
Remove unused code.

2023-01-13 15:16 UTC, renie commented on screen/send/details.js
> +import { MINI_AMOUNT } from '@env';
Lets call this var something more meaningful. Lets use "DUST_THRESHOLD".

2023-01-14 12:22 UTC, renie approved these changes

2023-01-16 06:45 UTC, merged