Testnet changes
mintlayer/mojito_mobile_wallet pull request #88
Opened 2023-02-14 16:19 UTC by ZainAliSyed24

- Test net changes merging to master till **commit 4ea17be**

2023-02-15 06:36 UTC, muursh reviewed
I have no real qualms here. 1) is the app-release.aab binary needed? 2) I haven't run this so won't approve right now but no real issues from my side

2023-02-15 09:04 UTC, ZainAliSyed24 commented
> qualms

**app-release.aab** file is for play store uploading  only for making release to production or internal testing  .

2023-02-15 09:06 UTC, muursh commented
Does it need to be on github though?

2023-02-15 09:09 UTC, ZainAliSyed24 commented
> eed to be on github th

I am going to  add this in gitignore file , so we don't have this in future , either  **apk** or .**abb** file both

2023-02-24 10:19 UTC, renie requested changes
Just very minor stuff.
Good job!

2023-02-24 10:19 UTC, renie commented on components/TransactionsNavigationHeader.js
> +  // {
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on components/WalletsCarousel.js
> +        <LinearGradient shadowColor={colors.shadowColor} colors={WalletGradient.gradientsFor(item.type)} style={iStyles.grad}>
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on components/WalletsCarousel.js
>              {/* <Text style={[iStyles.btcInfo, { color: colors.inverseForegroundColor, fontFamily: type.semiBold }]}>{'571915' + '    '}</Text>
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on ios/BlueWallet/Info.plist
> +	<!-- <array>
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on ios/BlueWallet/Info.plist
> +	</array> -->
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on screen/wallets/add.js
>            {/* <BitcoinButton testID="ActivateBitcoinButton" active={selectedWalletType === ButtonSelected.ONCHAIN} onPress={handleOnBitcoinButtonPressed} style={styles.button} /> */}
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on screen/wallets/add.js
> +          {/* <VaultButton active={selectedWalletType === ButtonSelected.VAULT} onPress={handleOnVaultButtonPressed} style={styles.button} /> */}
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on screen/wallets/list.js
> +          // if (dataSource.length === 1 && !isLoading) {
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on screen/wallets/transactions.js
> +          {/* wallet.chain === Chain.OFFCHAIN && renderMarketplaceButton() */}
Remove comments, please.

2023-02-24 10:19 UTC, renie commented on screen/wallets/transactions.js
> +    // return (
Remove comments, please.

2023-04-12 17:26 UTC, renie approved these changes

2023-04-12 17:27 UTC, merged